CPP      = g++.exe -D__DEBUG__
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include"

all: dataAnalysisMisc.dll

dataAnalysisMisc.dll: 
	${CPP} -o dataAnalysisMisc.dll tests.c -shared ${INCS} -fPIC

clean: 
	rm *.o *.dll
